### ISSUE TITLE
Make this extension more user friendly.

### ISSUE THREAD

**Issue by lowkeylif3** [amkhrjee/fontonic-firefox-android#1]
Hello, really thanks for this extension working great on my MOTOROLA device but i find it really pain to manually set font for all site.

Few suggestion; 
1. Select a font and use it as global for all website.
2. Option to select global font for all website & also specific font for individual sites.

**Comment by amkhrjee** [comment]
Sure thing. These features are actually already there in the [Chrome version](https://chromewebstore.google.com/detail/fontonic-change-fonts/hnjlnpipbcbgllcjgbcjfgepmeomdcog). However, I won’t be able to work on this for about a week, so you may need to wait a bit :)

**Comment by lowkeylif3** [comment]
> Sure thing. However, I won’t be able to work on this for about a week, so you may need to wait a bit :)
> 
> Also, these features are actually already there in the [Chrome version](https://chromewebstore.google.com/detail/fontonic-change-fonts/hnjlnpipbcbgllcjgbcjfgepmeomdcog).

No problem take your time.

Yes already using fontonic-chrome extension on my desktop works really well, but chrome doesn't have extension support on android yet tho.

One more thing I'm using *Nunito-Font* in fontonic extension on my android device which is same as *Verdana-Font* it doesn't work on most of the site anything can be done for this?
Few non working site:
github
gitlab
redlib
f-droid

BTW this font works absolutely fine on desktop in every site.
